# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8bf19358d349d777d6154eda0434b2e4e2c5176053831f54d013e7dd2c6a43add45569fac533e9b1cb9cbf792c2ec5f579eb214922cf101d279410fce167ff39

test:
  secret_key_base: 3234c3c95c46455c4e1794bde434aba4fb5a6e8ec919af597f88d7d95d6aa340ff40fe8ec164126a05226784b1ac0be22ee36207d0d596811c721f1d5c86c04a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
